export const REQUEST_LEADERBOARDS = "REQUEST_LEADERBOARDS";
export const RECEIVE_LEADERBOARDS = "RECEIVE_LEADERBOARDS";
export const ERROR_RECEIVING_LEADERBOARDS = "ERROR_RECEIVING_LEADERBOARDS";
export const NEXT_LEADERBOARD = "NEXT_LEADERBOARD";

export const UPDATE_ENTRY_LOCALLY = "UPDATE_ENTRY_LOCALLY";
export const SAVING_ENTRY = "SAVING_ENTRY";
export const ENTRY_SAVED = "ENTRY_SAVED";
export const ERROR_SAVING_ENTRY = "ERROR_SAVING_ENTRY";
export const CANCEL_ENTRY = "CANCEL_ENTRY";
