export const REQUEST_CONTESTS = "REQUEST_CONTESTS";
export const RECEIVE_CONTESTS = "RECEIVE_CONTESTS";
export const ERROR_RECEIVING_CONTESTS = "ERROR_RECEIVING_CONTESTS";
export const NEXT_CONTEST = "NEXT_CONTEST";

export const UPDATE_ENTRY_LOCALLY = "UPDATE_ENTRY_LOCALLY";
export const SAVING_ENTRY = "SAVING_ENTRY";
export const ENTRY_SAVED = "ENTRY_SAVED";
export const ERROR_SAVING_ENTRY = "ERROR_SAVING_ENTRY";
export const CANCEL_ENTRY = "CANCEL_ENTRY";
