export const REQUEST_CONTESTS = "REQUEST_CONTESTS";
export const RECEIVE_CONTESTS = "RECEIVE_CONTESTS";
export const ERROR_RECEIVING_CONTESTS = "ERROR_RECEIVING_CONTESTS";
export const NEXT_CONTEST = "NEXT_CONTEST";
